### ISSUE TITLE
AttributeError: type object 'Runtime' has no attribute 'PYTHON_3_10'

### ISSUE THREAD

**Issue by alexiswl** [umccr/samplesheet-check-backend#38]
Auto-deployment has the following issues 

```pytb
Traceback (most recent call last):
317 | File "/codebuild/output/src762825554/src/app.py", line 47, in <module>
318 | PipelineStack(
319 | File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
320 | inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
321 | File "/codebuild/output/src762825554/src/stacks/pipeline_stack.py", line 122, in __init__
322 | SampleSheetCheckBackEndStage(
323 | File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
324 | inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
325 | File "/codebuild/output/src762825554/src/stacks/pipeline_stack.py", line 22, in __init__
326 | SampleSheetCheckBackEndStack(
327 | File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
328 | inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
329 | File "/codebuild/output/src762825554/src/stacks/sscheck_backend_stack.py", line 60, in __init__
330 | compatible_runtimes=[lambda_.Runtime.PYTHON_3_10],
331 | AttributeError: type object 'Runtime' has no attribute 'PYTHON_3_10'
332 |  
333 | Subprocess exited with error 1
334
```

**Comment by alexiswl** [comment]
Upgrading CDK versions should fix this
